site_name: DataForge
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_python_path: [.]
          options:
            show_source: true
            members_order: alphabetical

nav:
  - Home: index.md
  - Operations:
      - base operation: operations/file_operation.md
      - move: operations/move.md
      - delete: operations/delete.md
      - slice: operations/slice.md
      - dedup: operations/deduplicate.md
      - clean-annotations: operations/clean_annotations.md
      - convert-annotations: operations/convert_annotations.md
      - stats: operations/stats.md
  - API Reference:
      - Main: api/data_forge.md
      - Image Comparer: api/img_comparer.md
      - Video slicer: api/video_slicer.md
      - CacheIO: api/cache_io.md
      - Hasher:
          - Base Hasher: api/base_hasher.md
          - DHash: api/dhash.md
      - Annotation Converter:
          - Base Converter: api/base_converter.md
          - VOC to YOLO converter: api/voc_yolo_converter.md
          - YOLO to VOC converter: api/yolo_voc_converter.md
      - Reader:
          - Base reader: api/base_reader.md
          - XML reader: api/xml_reader.md
          - TXT reader: api/txt_reader.md
      - Writer:
          - Base writer: api/base_writer.md
          - XML writer: api/xml_writer.md
          - TXT writer: api/yolo_writer.md
      - Mixins:
          - FileRemoverMixin: api/file_remover.md
      - Stats:
          - Feature extractor: api/feature_extractor.md
          - Image Analyzer: api/image_analyzer.md
          - Outlier Detector: api/outlier_detector.md
          - Base Stats: api/base_stats.md
          - Yolo Stats: api/yolo_stats.md
          - VOC Stats: api/voc_stats.md
          - Reporter:
                - Base Reporter: api/base_reporter.md
                - Image Dataset Reporter: api/image_reporter.md
  - CLI:
      - CLI launching: cli/data_forge.md
      - Default Settings: cli/default_values.md