site_name: DataForge
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_python_path: [.]
          options:
            show_source: true
            members_order: alphabetical

nav:
  - Home: index.md
  - Operations:
      - base operation: operations/file_operation.md
      - move: operations/move.md
      - delete: operations/delete.md
      - slice: operations/slice.md
      - dedup: operations/deduplicate.md
      - clean-annotations: operations/clean_annotations.md
      - convert-annotations: operations/convert_annotations.md
  - API Reference:
      - Image Comparer: api/img_comparer.md
      - Hasher:
          - Base Hasher: api/base_hasher.md
          - DHash: api/dhash.md
      - Annotation Converter:
          - Base Converter: api/converter.md
          - VOC to YOLO converter: api/voc_yolo_converter.md
          - YOLO to VOC converter: api/yolo_voc_converter.md
  - CLI:
      - CLI launching: cli/data_forge.md
      - Default Settings: cli/default_values.md